// <auto-generated />
using System;
using CS_final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS_final.Migrations
{
    [DbContext(typeof(ClubDbContext))]
    [Migration("20211206212640_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CS_final.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Full_name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CS_final.Models.Equipment", b =>
                {
                    b.Property<long>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CS_final.Models.EquipmentUsage", b =>
                {
                    b.Property<long>("EquipmentUsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<long?>("EquipmentID1")
                        .HasColumnType("bigint");

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<long?>("GameID1")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("SnapPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquipmentUsageID");

                    b.HasIndex("EquipmentID1");

                    b.HasIndex("GameID1");

                    b.ToTable("EquipmentUsages");
                });

            modelBuilder.Entity("CS_final.Models.Game", b =>
                {
                    b.Property<long>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<long?>("CustomerID1")
                        .HasColumnType("bigint");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<long?>("LocationID1")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayersCount")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.HasIndex("CustomerID1");

                    b.HasIndex("LocationID1");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CS_final.Models.Location", b =>
                {
                    b.Property<long>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CS_final.Models.EquipmentUsage", b =>
                {
                    b.HasOne("CS_final.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID1");

                    b.HasOne("CS_final.Models.Game", null)
                        .WithMany("EquipmentUsages")
                        .HasForeignKey("GameID1");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CS_final.Models.Game", b =>
                {
                    b.HasOne("CS_final.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID1");

                    b.HasOne("CS_final.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID1");

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CS_final.Models.Game", b =>
                {
                    b.Navigation("EquipmentUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
